name: /nethome/4291387/parcels_env
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asciitree=0.3.3=py_2
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.1.0=py312h06a4308_0
  - aws-c-auth=0.8.1=h205f482_0
  - aws-c-cal=0.8.1=h1a47875_3
  - aws-c-common=0.10.6=hb9d3cd8_0
  - aws-c-compression=0.3.0=h4e1184b_5
  - aws-c-event-stream=0.5.0=h7959bf6_11
  - aws-c-http=0.9.2=hefd7a92_4
  - aws-c-io=0.15.3=h173a860_6
  - aws-c-mqtt=0.11.0=h11f4f37_12
  - aws-c-s3=0.7.9=he1b24dc_1
  - aws-c-sdkutils=0.2.2=h4e1184b_0
  - aws-checksums=0.2.2=h4e1184b_4
  - aws-crt-cpp=0.29.9=he0e7f3f_2
  - aws-sdk-cpp=1.11.489=h4d475cb_0
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - binutils=2.40=hdd6e379_0
  - binutils_impl_linux-64=2.40=hf600244_0
  - binutils_linux-64=2.40=hbdbef99_2
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.3.4=pyhd8ed1ab_0
  - bottleneck=1.4.2=py312hc0a28a1_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.34.4=hb9d3cd8_0
  - c-compiler=1.7.0=hd590300_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cartopy=0.22.0=py312hfb8ada1_1
  - certifi=2025.1.31=py312h06a4308_0
  - cf_xarray=0.9.0=pyhd8ed1ab_0
  - cftime=1.6.3=py312hc7c0aa3_0
  - cgen=2020.1=py_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py312h8572e83_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py312h98912ed_0
  - dask=2024.2.1=pyhd8ed1ab_0
  - dask-core=2024.2.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py312h30efb56_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2024.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonttools=4.49.0=py312h98912ed_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2024.2.0=pyhca7485f_0
  - gcc=12.3.0=h8d2909c_2
  - gcc_impl_linux-64=12.3.0=he2b93b0_5
  - gcc_linux-64=12.3.0=h76fc315_2
  - geos=3.12.1=h59595ed_0
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.7.1=hbabe93e_0
  - h3-py=4.2.2=py312h2ec8cdc_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.4=nompi_h2d575fe_105
  - icu=73.2=h59595ed_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - ipywidgets=8.1.6=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jsonschema=4.19.2=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - jupyterlab_widgets=3.0.14=pyhd8ed1ab_0
  - kaleido-core=0.2.1=h7c8854e_0
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libarrow=17.0.0=h461ed7b_47_cpu
  - libarrow-acero=17.0.0=hcb10f89_47_cpu
  - libarrow-dataset=17.0.0=hcb10f89_47_cpu
  - libarrow-flight=17.0.0=h0b6dd73_47_cpu
  - libarrow-flight-sql=17.0.0=h96f74d6_47_cpu
  - libarrow-gandiva=17.0.0=h1a3b679_47_cpu
  - libarrow-substrait=17.0.0=h08228c5_47_cpu
  - libblas=3.9.0=21_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=21_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=12.3.0=h8bca6fd_105
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.2.0=h767d61c_2
  - libgoogle-cloud=2.34.0=h2b5623c_0
  - libgoogle-cloud-storage=2.34.0=h0121fbd_0
  - libgrpc=1.67.1=h25350d4_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=21_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm16=16.0.6=hb3ce162_3
  - libllvm18=18.1.8=h8b73ec9_2
  - libnetcdf=4.9.2=nompi_h2564987_115
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.16=h0b41bf4_1
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libparquet=17.0.0=h081d1f1_47_cpu
  - libpng=1.6.46=h943b412_0
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - libsanitizer=12.3.0=h0f45ef3_5
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libutf8proc=2.10.0=h4c51ac1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.42.0=py312h6a678d5_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py312hf0f0c11_2
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=2.1.5=py312h98912ed_0
  - mathjax=2.7.5=h06a4308_0
  - matplotlib-base=3.8.3=py312he5832f3_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - msgpack-python=1.0.7=py312h8572e83_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.9.2=py312h06a4308_0
  - nbstripout=0.8.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf4=1.7.2=nompi_py312ha728dd9_101
  - nspr=4.35=h6a678d5_0
  - nss=3.105=hd34e28f_0
  - numba=0.59.1=py312hacefee8_0
  - numba-scipy=0.2.0=py_1
  - numcodecs=0.12.1=py312h30efb56_0
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.5.0=h7b32b05_0
  - orc=2.0.3=h12ee42a_2
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.2.1=py312hfb8ada1_0
  - parcels=3.0.2=pyh779afd3_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - patsy=0.5.6=py312h06a4308_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py312hdcec9eb_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - plotly=5.22.0=py312he106c6f_0
  - plotly_express=0.4.1=py_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - proj=9.3.1=h1d62c97_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py312h98912ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=17.0.0=py312h9cebb41_2
  - pyarrow-core=17.0.0=py312h01725c0_2_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pymbolic=2022.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.6.1=py312h38f1c37_5
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.1.0=pyhd8ed1ab_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=py312h06a4308_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytools=2023.1.1=pyhd8ed1ab_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - pyzmq=25.1.2=py312h886d080_0
  - rdma-core=50.0=hd3aeb46_0
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py312h06a4308_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - ruff=0.11.5=py312h286b59f_0
  - s2n=1.5.11=h072c03f_0
  - scipy=1.12.0=py312heda63a1_2
  - setuptools=69.1.1=pyhd8ed1ab_0
  - shapely=2.0.3=py312h9e6bd2c_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h8bd8927_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.49.1=h9eae976_2
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.2=py312ha883a20_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tblib=3.0.0=pyhd8ed1ab_0
  - tenacity=8.2.3=py312h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py312h98912ed_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - trajan=0.3.2=pyhd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucx=1.15.0=h75e419f_3
  - urllib3=2.2.1=pyhd8ed1ab_0
  - utide=0.3.0=pyhd8ed1ab_0
  - utm=0.7.0=pyhd8ed1ab_0
  - version_information=1.0.4=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xarray=2024.2.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zarr=2.17.0=pyhd8ed1ab_0
  - zeromq=4.3.5=h59595ed_1
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - astropy==6.1.4
      - astropy-iers-data==0.2024.10.7.0.32.46
      - beautifulsoup4==4.12.3
      - branca==0.8.0
      - charset-normalizer==3.3.2
      - click-plugins==1.1.1
      - cligj==0.7.2
      - dill==0.3.9
      - duckdb==1.1.1
      - fiona==1.10.1
      - folium==0.17.0
      - future==1.0.0
      - geoarrow-c==0.1.2
      - geoarrow-pandas==0.1.1
      - geoarrow-pyarrow==0.1.2
      - geodatasets==2024.8.0
      - geographiclib==2.0
      - geojson==3.1.0
      - geopandas==0.14.4
      - geopy==2.4.1
      - h3==4.1.0b3
      - h3ronpy==0.21.1
      - hampel==1.0.2
      - haversine==2.8.1
      - idna==3.10
      - joblib==1.4.2
      - mapclassify==2.8.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - networkx==3.3
      - osmnx==1.9.4
      - overpass==0.7
      - polars==1.9.0
      - pooch==1.8.2
      - pyerfa==2.0.1.4
      - pyfunctional==1.5.0
      - pymap3d==3.1.0
      - quackosm==0.11.0
      - requests==2.32.3
      - rich==13.9.2
      - s2==0.1.9
      - s2sphere==0.2.5
      - scikit-learn==1.5.2
      - soupsieve==2.6
      - spherical-geometry==1.3.2
      - srai==0.7.7
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - topojson==1.9
      - typeguard==4.3.0
prefix: /nethome/4291387/parcels_env
